#!/bin/sh

# usage: generate_statistics <binary file> <file containing the shared library load addresses> <file containing the sampled addresses>

cat $2 $3 | ./backtrace $1 ld.lib.so | sed -e '/Scanned image/d' | sort | uniq --count | sort -rn > statistics_by_function.txt
echo "statistics_by_function.txt generated"

cat $3 | sort | uniq --count | sort -rn | cat $2 - | ./backtrace $1 ld.lib.so | sed -e '/Scanned image/d' > statistics_by_address.txt
echo "statistics_by_address.txt generated"
