#
# Ubuntu 18.04 64bit in VBox 5
#

assert_spec x86_64
assert_spec nova

set flavor   "debian"
set vm_ram   "2048M"

set use_vbox5 1

set use_rumpfs 1
# Write overlay only into ram
set use_ram_fs 1
# However read initial overlay from disk
set use_overlay_from_disk 1

set use_usb 1
set use_ps2 [have_spec ps2]

set use_vms 1
set use_cpu_load 0

# use non-generic vbox5 VMM version
set use_vbox5_nova 1

source ${genode_dir}/repos/ports/run/vbox_win.inc
