PKG_DIR := $(call select_from_ports,tcl)/src/noux-pkg/tcl

#
# Prevent the following error: "/.../genode-*-strip: /.../noux-pkg/tcl/install//bin/_inst.3074851_: file format not recognized"
#
INSTALL_TARGET := install

$(INSTALL_DIR)/libtcl8.6.lib.so: built.tag
	$(VERBOSE)ln -sf $(PWD)/install/lib/libtcl8.6.lib.so $@

installed.tag: $(INSTALL_DIR)/libtcl8.6.lib.so

include $(call select_from_repositories,mk/noux.mk)

CONFIGURE_ARGS += "--disable-rpath"
CONFIGURE_ARGS += "--disable-threads"
CONFIGURE_ARGS += "tcl_cv_sys_version=FreeBSD-12.0-RELEASE"
CONFIGURE_ARGS += "ac_cv_func_strtod=yes"
CONFIGURE_ARGS += "tcl_cv_strtod_buggy=1"

CONFIGURE_SCRIPT = $(PKG_DIR)/unix/configure

# Pass the correct strip program to 'install-sh'
MAKE_ENV += "STRIPPROG=$(STRIP)"

LIBS += ldso_so_support

#
# By default, tclsh is generated with a hidden 'main' symbol, which cannot
# be found by Genode's dynamic linker. Since this behavior is not configurable,
# we need to patch the Makefile generated by the configure script.
#
tweak_makefile.tag: Makefile
tweak_makefile.tag:
	$(VERBOSE)echo "AC_FLAGS += -UMODULE_SCOPE" >> Makefile
	@touch $@
built.tag: tweak_makefile.tag

Makefile: dummy_libs

.SECONDARY: dummy_libs
dummy_libs: libdl.a

libdl.a:
	$(VERBOSE)$(AR) -rc $@
