source ${genode_dir}/repos/os/run/monitor_gdb2.inc

# sequence of GDB commands to execute at startup
set gdb_cmds ""
append gdb_cmds {-ex "set non-stop on" }
append gdb_cmds {-ex "set pagination off" }
append gdb_cmds {-ex "target extended-remote localhost:$local_port" }

# run GDB
eval spawn [gdb] debug/ld.lib.so -n $gdb_cmds
set gdb_id [list $spawn_id $genode_id]

# show output of both GDB and Genode, supply user input to GDB
interact -i $gdb_id $genode_id
