#!/bin/sh

./genode_qt_configure

# qtbase

cd qtbase/src/corelib                        && ../../../create_generated_inc qt_core              && cp qt_core_generated.inc ../../..              && cd ../../..
cd qtbase/src/gui                            && ../../../create_generated_inc qt_gui               && cp qt_gui_generated.inc ../../..               && cd ../../..
cd qtbase/src/network                        && ../../../create_generated_inc qt_network           && cp qt_network_generated.inc ../../..           && cd ../../..
#cd src/scripttools                           && ../../create_generated_inc qt_scripttools          && cp qt_scripttools_generated.inc ../..          && cd ../..
#cd src/svg                                   && ../../create_generated_inc qt_svg                  && cp qt_svg_generated.inc ../..                  && cd ../..
cd qtbase/src/widgets                        && ../../../create_generated_inc qt_widgets           && cp qt_widgets_generated.inc ../../..           && cd ../../..
cd qtbase/src/xml                            && ../../../create_generated_inc qt_xml               && cp qt_xml_generated.inc ../../..               && cd ../../..

#cd tools/designer/src/uitools                && ../../../../create_generated_inc qt_ui_tools       && cp qt_ui_tools_generated.inc ../../../..       && cd ../../../..

# qtwebkit

make -C qtbase/src/tools

make -C qtwebkit/Source/JavaScriptCore -f Makefile.JavaScriptCore sub-DerivedSources-pri
cd qtwebkit/Source/JavaScriptCore
../../../qtbase/bin/qmake ../../../../qt-everywhere-opensource-src-5.0.2/qtwebkit/Source/JavaScriptCore/Target.pri -o Makefile
                                                ../../../create_generated_inc qt_jscore            && cp qt_jscore_generated.inc ../../..      && cd ../../..

#make -C qtwebkit/Source/WebCore -f Makefile.WebCore sub-DerivedSources-pri


#cd src/3rdparty/webkit/Source/JavaScriptCore && ../../../../../create_generated_inc qt_jscore      && cp qt_jscore_generated.inc ../../../../..      && cd ../../../../..
#cd src/3rdparty/webkit/Source/WebCore        && ../../../../../create_generated_inc qt_webcore     && cp qt_webcore_generated.inc ../../../../..     && cd ../../../../..
#cd src/3rdparty/webkit/Source/WebKit/qt      && ../../../../../../create_generated_inc qt_webkit   && cp qt_webkit_generated.inc ../../../../../..   && cd ../../../../../..

