#!/bin/sh

../qt-everywhere-opensource-src-5.2.1/configure \
    -opensource \
    -confirm-license \
    -qconfig genode \
    -xplatform genode-g++ \
    -no-qpa-platform-guard \
    -qpa minimal \
    -fully-process \
    -no-separate-debug-info \
    -opengl desktop \
    -openssl-linked \
    -no-accessibility \
    -no-cups \
    -no-dbus \
    -no-iconv \
    -no-largefile \
    -no-nis \
    -no-pkg-config \
    -no-xcb \
    -no-sse2 \
    -no-sse3 \
    -no-ssse3 \
    -no-sse4.1 \
    -no-sse4.2 \
    -no-avx \
    -no-neon \
    -make tools \
    -nomake examples

#
# notes
#
# - '-no-opengl' would prevent the generation of qtwebkit Makefiles
#
#
