#!/bin/sh

../qt-everywhere-opensource-src-5.8.0/configure \
    -opensource \
    -confirm-license \
    -no-separate-debug-info \
    -no-sse3 \
    -no-ssse3 \
    -no-sse4.1 \
    -no-sse4.2 \
    -no-avx \
    -no-avx2 \
    -no-avx512 \
    -no-reduce-relocations \
    -no-pch \
    -no-use-gold-linker \
    -make tools \
    -nomake examples \
    -no-dbus \
    -no-accessibility \
    \
    -no-glib \
    -no-eventfd \
    -no-inotify \
    -no-iconv \
    -no-icu \
    -qt-pcre \
    -system-zlib \
    -no-feature-poll_ppoll \
    -no-feature-threadsafe-cloexec \
    \
    -openssl-linked \
    -no-system-proxies \
    \
    -no-cups \
    -no-fontconfig \
    -system-freetype \
    -no-harfbuzz \
    -opengl desktop \
    -qpa minimal \
    -no-xcb \
    -system-libjpeg \
    -system-libpng \
    \
    -qt-sqlite
