build "core init test/big_ds_alloc"

create_boot_directory

install_config {
	<config>
		<parent-provides>
			<service name="LOG"/>
		</parent-provides>
		<default-route>
			<any-service> <parent/> </any-service>
		</default-route>
		<start name="test-big_ds_alloc">
			<resource name="RAM" quantum="2G"/>
		</start>
	</config>
}

build_boot_image "core init test-big_ds_alloc"

append qemu_args "-nographic -m 2048"

run_genode_until forever
